# Generated by Django 5.2.7 on 2025-10-29 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_sensordata_jenis_buah'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordata',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
