# Generated by Django 5.2.8 on 2025-11-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_rename_created_at_sensordata_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='gas',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='mq135',
            field=models.FloatField(blank=True, help_text='Amonia/CO₂ (ppm)', null=True, verbose_name='Gas MQ135'),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='mq2',
            field=models.FloatField(blank=True, help_text='Gas umum (ppm)', null=True, verbose_name='Gas MQ2'),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='mq3',
            field=models.FloatField(blank=True, help_text='Alkohol/VOC (ppm)', null=True, verbose_name='Gas MQ3'),
        ),
    ]
